# Generated by Django 4.1.2 on 2022-10-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='New', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tracker_app.status', verbose_name='Статус'),
        ),
    ]
